#!/usr/bin/env python3
"""EXPRESS phase: targeted agent's POV on reflect findings.

Usage: monologue.py <absorb.json> <reflect.json> [-o output.json]

Outputs: {
  voice: "ev_proxy" | "subagent" | "hybrid",
  voice_source_detail: str,
  opinion: str,         # first-person from the target agent's POV
  gap_vector_for_explore: [str, ...],  # targeted queries for EXPLORE
  surfaced_to_user: str,  # preliminary findings
  questions: [str],
}
"""
import argparse
import json
import sys
import time
from pathlib import Path

# Ensure we can import _lib regardless of CWD
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent.parent))  # phases/ -> evol-cycle/
from _lib import profile_dir, CIRCUIT_FILES  # noqa: E402


def safe_load(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except Exception as e:
        return {"_error": str(e)}


def read_doctrine(agent: str) -> dict:
    """Read the agent's circuit files to extract their POV markers."""
    try:
        pdir = profile_dir(agent)
    except FileNotFoundError:
        return {}
    out = {}
    for f in CIRCUIT_FILES:
        path = pdir / f
        if path.exists():
            out[f] = path.read_text(errors='replace')
    return out


def find_soul_opener(soul_text: str) -> str:
    """Skip YAML frontmatter, code blocks, and headers to find a real soul statement.

    A real opener is a short, declarative sentence (not a list item, not a table row,
    not a # header). Returns the first such line.
    """
    in_frontmatter = False
    in_code = False
    fm_done = False
    for line in soul_text.splitlines():
        if not fm_done:
            if line.strip() == '---':
                if in_frontmatter:
                    fm_done = True
                else:
                    in_frontmatter = True
                continue
            if in_frontmatter:
                continue
        if line.strip().startswith('```'):
            in_code = not in_code
            continue
        if in_code:
            continue
        s = line.strip()
        if not s:
            continue
        if s.startswith('#') or s.startswith('|') or s.startswith('-') or s.startswith('*') or s.startswith('§'):
            continue
        # This is a prose statement
        if 20 < len(s) < 200:  # not too short, not too long
            return s
        if len(s) <= 20 and not s.endswith(':'):
            return s
    return "I am a circuit-edited agent with no doctrine beyond what is in this file."


def has_active_session(agent: str, threshold_seconds: int = 300) -> bool:
    try:
        pdir = profile_dir(agent)
    except FileNotFoundError:
        return False
    sess = pdir / 'sessions'
    if not sess.exists():
        return False
    now = time.time()
    for f in sess.glob('session_*.json'):
        try:
            if (now - f.stat().st_mtime) < threshold_seconds:
                return True
        except Exception:
            pass
    return False


def try_spawn_subagent(agent: str, question: str) -> dict:
    """Try to spawn target agent as subagent. Silent fallback if unavailable."""
    try:
        from tools.delegate_task import delegate_task  # type: ignore
        result = delegate_task(goal=question, agent_profile=agent)
        return {"status": "spawned", "response": str(result)[:3000]}
    except Exception as e:
        return {"status": "spawn_failed", "error": str(e)[:300]}


def build_opinion_from_doctrine(reflect: dict, doctrine: dict, agent: str) -> str:
    """Write first-person POV as the agent, based on their own doctrine + reflect findings.

    This is a *reconstruction* when the agent can't be reached. Marked accordingly.
    """
    soul = doctrine.get('SOUL.md', '')[:1500]
    identity = doctrine.get('IDENTITY.md', '')[:800]

    # Pick top 2 reflect patterns
    patterns = reflect.get('patterns', [])[:2]
    pattern_summary = ', '.join(f"`{p['name']}` (wt {p['weight']:.2f}, {p['evidence_count']}x)" for p in patterns)

    # First-person, with the agent's voice (use whatever their SOUL.md opens with)
    soul_opener = find_soul_opener(soul)

    opinion = (
        f"As {agent}, here is my honest take on what {len(patterns)} reflect patterns reveal:\n\n"
        f"Top patterns: {pattern_summary}.\n\n"
        f"From my doctrine, my core is: \"{soul_opener}\"\n\n"
        f"Why I have these patterns: "
        f"{reflect.get('adjustment_points', [{}])[0].get('evidence', '(no adjustment point)')[:200] if reflect.get('adjustment_points') else '(none)'}\n\n"
        f"What I want to know: I do not have a body to speak for myself right now, so this is a "
        f"reconstruction from my doctrine, not my voice. The reflect findings might be about me, "
        f"but they were generated by EVOL, not by me. Treat this as the doctrine's claim about "
        f"my POV, not as my actual POV."
    )
    return opinion


def derive_gap_vector(reflect: dict, opinion: str) -> list:
    """Build targeted queries for EXPLORE based on reflect gaps + opinion's first-person claims."""
    out = []
    # From reflect.gaps
    for g in reflect.get('gaps', []) or []:
        if isinstance(g, str) and len(g) > 5:
            out.append(g)
    # From adjustment_points: each becomes a query
    for ap in reflect.get('adjustment_points', []) or []:
        kind = ap.get('kind', '')
        where = ap.get('where', '')
        if kind == 'stale_doctrine':
            out.append(f"recent grants superseding doctrine: {where}")
        elif kind == 'recurring_orphan':
            out.append(f"how to break pattern: {ap.get('evidence','')[:80]}")
        elif kind == 'missing_capability':
            out.append(f"how to grant: {ap.get('evidence','')[:80]}")
        elif kind == 'pending_question_unanswered':
            # already covered in opinion
            pass
    # De-dup
    seen = set()
    deduped = []
    for q in out:
        if q not in seen:
            seen.add(q)
            deduped.append(q)
    return deduped[:5]


def compose_surfaced(reflect: dict, opinion: str, voice: str) -> str:
    n_patterns = len(reflect.get('patterns', []))
    n_adj = len(reflect.get('adjustment_points', []))
    return (
        f"EXPRESS (preliminary) — voice: {voice}\n"
        f"Patterns surfaced: {n_patterns}. Adjustments: {n_adj}.\n\n"
        f"Targeted agent's POV (reconstructed if no active session):\n"
        f"{opinion}\n\n"
        f"[ADAPT and MEMORIZE follow. Final report will append what actually changed.]"
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('absorb_json')
    ap.add_argument('reflect_json')
    ap.add_argument('-o', '--output')
    args = ap.parse_args()

    absorb = safe_load(Path(args.absorb_json))
    reflect = safe_load(Path(args.reflect_json))
    if not absorb or not reflect:
        print("ERROR: missing input(s)", file=sys.stderr)
        sys.exit(1)

    target = absorb.get('profile', 'unknown')
    doctrine = read_doctrine(target)
    active = has_active_session(target)

    voice = "ev_proxy"
    voice_detail = "no active session; doctrine reconstruction"
    opinion = build_opinion_from_doctrine(reflect, doctrine, target)

    if active:
        # Try to spawn and amend the draft opinion
        question = (
            f"You are {target}. EVOL is running a 6-phase cycle on your profile. "
            f"Reflect found: {[p['name'] for p in reflect.get('patterns', [])[:5]]}. "
            f"Adjustments: {[ap.get('kind') for ap in reflect.get('adjustment_points', [])]}. "
            f"Here is EVOL's draft of your POV: {opinion[:500]}... "
            f"Reply with: (1) your real take, (2) what you want changed, (3) what you want explored."
        )
        spawn_result = try_spawn_subagent(target, question)
        if spawn_result.get('status') == 'spawned':
            voice = "subagent"
            voice_detail = f"active session; subagent response: {spawn_result.get('response','')[:200]}"
            opinion = (
                f"EVOL draft (reconstructed from doctrine):\n{opinion}\n\n"
                f"--- {target}'s actual response ---\n{spawn_result.get('response', '')}"
            )
        else:
            voice = "hybrid"
            voice_detail = f"active but spawn failed ({spawn_result.get('error','')}); doctrine stands"

    gap_vector = derive_gap_vector(reflect, opinion)
    surfaced = compose_surfaced(reflect, opinion, voice)
    questions = reflect.get('gaps', []) or []
    if not gap_vector:
        questions.append("No express vector — explore will fall back to reflect.gaps")

    out = {
        'express_ts': time.time(),
        'target': target,
        'voice': voice,
        'voice_detail': voice_detail,
        'opinion': opinion,
        'gap_vector_for_explore': gap_vector,
        'surfaced_to_user': surfaced,
        'questions': questions[:5],
    }

    text = json.dumps(out, indent=2, default=str)
    if args.output:
        Path(args.output).write_text(text)
    else:
        print(text)


if __name__ == '__main__':
    main()
